# Generated by Django 4.2 on 2023-07-03 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_cartdb'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartdb',
            old_name='price',
            new_name='productname',
        ),
        migrations.RenameField(
            model_name='cartdb',
            old_name='totalpprice',
            new_name='totalprice',
        ),
    ]
