# Generated by Django 4.2 on 2023-07-03 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_rename_price_cartdb_productname_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartdb',
            old_name='describtion',
            new_name='description',
        ),
    ]
